[logging]
level = "debug"      # "debug", "info", "warn" or "error"

[auth]
papik_chat_id = 1357068827

[telegram]
database_directory = "./tdlib_session"
api_hash = "59d2ab11cd511544a4655e981f8c39b6"
api_id = 33077431